logging:
  level:
    com:
      ts:
        employee:
          api: INFO
    org:
      springframework:
        web: INFO
    root: INFO
server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
